### ISSUE TITLE
API for discrepancy data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#120]
# Description

We have information on discrepancies across multiple records for the same trial. This info needs to be exposed via the API for usage on Trial Detail pages.

# Tasks

- TBD

**Comment by pwalsh** [comment]
Requires spec from @vitorbaptista

**Comment by vitorbaptista** [comment]
Fixed in https://github.com/opentrials/api/pull/55

There isn't an actual endpoint for the discrepancy data, but an endpoint to list `records` related to a `trial` (`/trials/{id}/records`) and a new `has_discrepancies` attribute in the trial. With these two things, we can show the discrepancies in the Explorer (https://github.com/opentrials/opentrials/pull/184)
