### ISSUE TITLE
Extract age information from trials

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#173]
For the registries and trials that have it, we should extract the age range of the participants.

**Comment by arthurSena** [comment]
@vitorbaptista Me and @aramisaraujo will be tackling this issue. Our idea is to use the 'eligibility_criteria'
column from the 'trials' table in order to figure out what is the age range of the participants. 
This column's type is jsonb and already has two keys (maximun_age and minimun_age). 

This way, we thought about using them to implement the age range column as jsonb to store this information. We found out that around 70% of the trials have these two keys in the 'eligibility_criteria' column. What do you think about this approach ?

**Comment by pwalsh** [comment]
@vitorbaptista phase I ?
