### ISSUE TITLE
Add breadcrumbs to the pages

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#216]
We already have the designs for it in our mockups:

http://opentrials.github.io/mockups/search-results.html
![search results page breadcrumbs](https://cloud.githubusercontent.com/assets/76945/16914013/c65d1466-4ce6-11e6-8622-9df1ac122f01.png)

http://opentrials.github.io/mockups/trial.html
![trial details page breadcrumbs](https://cloud.githubusercontent.com/assets/76945/16913998/a3eb97ae-4ce6-11e6-9244-748e8b818774.png)

# What to add in the breadcrumb?

## Search page

Just add the query string. That leaves the filters out for now. In the future, it would be nice to have a breadcrumb like:

> Search > `Depression` trials in `Brazil` or `UK`, `with published results` and `without discrepancies`.

But we can leave that for another task.

## Trial detail page

Add the name of the trial, but trim it after `x` characters so the breadcrumb doesn't appear too big

**Comment by nightsh** [comment]
I looked at some libraries, aiming for a mix of knowledge on what others did and how they did it. Nothing deeply satisfying, so I proceeded with looking into the request and its friends' contents.

Following my dissection of hapi's request / response structure, I found that I can use directly its properties, containing the path, route params and query string. Here is a mix of `request.path`, `request.params` and `request.query`. There are other built-in structures in there that might prove helpful in various situations, so this was a fruitful investigation.

I kept looking, hoping to find the title of the current document because I knew it was injected into template's context. So I found it in `request.response.source.context.title`.

These being said, the only 2 things I need to know now are:

* how to get a route's full URL with hapi, if I have its name (shouldn't be hard, haven't looked into it yet)
* if there are situations where we need the breadcrumb text to be different by the route actual name (e.g. *search* vs. *Explorer*) – @vitorbaptista, any idea?

The breadcrumbs are injected into templates via a(nother) request hook and the logic sits in a file inside `lib/plugins/` with the usual imports and exports around the code.

-----

There is one problem I have so far, and I am still trying to get to an elegant outcome for it. If you look at the mockups, you see the search results breadcrumb is atypical, i.e. it contains part of the query string. Usually, the breadcrumb contains the route name.

So what am I looking into now is to try adopting the least tightly coupled and invasive of these (quite obvious) solutions – or find a third:

* adding a "title" property to routes that can be either a string, a function call or a property's name
* add several helper functions in the breadcrumbs plugin that would treat the various cases and use a switch or similar in the exported function

**Comment by vitorbaptista** [comment]
@nightsh What about a simply hardcoding the breadcrumbs? The pages we have don't have a deep hierarchy between them. Out of the top of my mind, I can think of:

> Search > _search query_
> Search > _trial name_
> Search > _trial name_ > _source id_
> Search > _trial name_ > Contribute data

We shouldn't change the page layout too much depending on which page you're in, which means every page should have a breadcrumb, even those where a breadcrumb is somewhat useless (e.g. About page, search page before a query was made, ...)

**Comment by nightsh** [comment]
Doing it tonight, I will produce a combination of your approach and mine ;)

**Comment by nightsh** [comment]
It's hardcoded behaviour in the breadcrumbs plugin, but dynamic stuff that gets injected and shown inside templates. I say it's a decent compromise, thus opening up the discussion / feedback loop on the implementation and moving over to #268.

**Comment by vitorbaptista** [comment]
Fixed by https://github.com/opentrials/opentrials/commit/ae8e010b30b3b98426a8d053829cb1964e0701a4
