### ISSUE TITLE
Forward slash / in search box gives '502 Bad Gateway' error

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#227]
I was searching for:

Hyaluronan and N-ERC/Mesothelin as Key Biomarkers in a Specific Two-Step Model to Predict Pleural Malignant Mesothelioma

http://explorer.opentrials.net/search?q=Hyaluronan+and+N-ERC%2FMesothelin+as+Key+Biomarkers+in+a+Specific+Two-Step+Model+to+Predict+Pleural+Malignant+Mesothelioma&sample_size_start=&sample_size_end=&gender=&has_published_results=&has_discrepancies=&registration_date_start=&registration_date_end=

And got the above error message - removing the / stops the problem.

**Comment by vitorbaptista** [comment]
This happens because we're using ElasticSearch query string on searching. This isn't recommended because there can be syntax errors. We might change to a [simple query string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html) that would still allow some advanced search features (like `AND`, `OR`, etc), while avoiding the possibility of syntax errors.

However, it also removes many features that we're using, like searching in specific fields, so it has to be done as part of a bigger change.

**Comment by roll** [comment]
Could be this forward slash escaped before ES?

**Comment by vitorbaptista** [comment]
@roll Good point. I've written about the drawbacks on escaping the query strings at https://github.com/opentrials/opentrials/pull/233. Please, take a look.
