### ISSUE TITLE
Discrepancies we're interested in?

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#234]
For example, the trial http://explorer.opentrials.net/trials/6d8b70f3-f56f-4901-8d92-f5cd51f4af82 has a discrepancy in the public title (see http://explorer.opentrials.net/trials/6d8b70f3-f56f-4901-8d92-f5cd51f4af82/discrepancies). However, there's no icon for it.

The issue is that we're adding the icons in the `trials-details.html` view, but the title is set by the layout with data from a context variable (`title`)

**Comment by vitorbaptista** [comment]
Taking a step back: are discrepancies on a trial's title interesting at all?

**Comment by roll** [comment]
Having our ideal model we could ask BenG:
- what fields from the ideal data model are interesting for discrepancies
- what fields outside the ideal data model are interesting for discrepancies

**Comment by vitorbaptista** [comment]
@opentrials/research could you answer @roll's questions?

**Comment by roll** [comment]
Current trial attributes:

```
            'primary_register'
            'primary_id'
            'identifiers'
            'registration_date'
            'public_title'
            'brief_summary'
            'scientific_title'
            'description'
            'recruitment_status'
            'eligibility_criteria'
            'target_sample_size'
            'first_enrollment_date'
            'study_type'
            'study_design'
            'study_phase'
            'primary_outcomes'
            'secondary_outcomes'
            'gender'
            'has_published_results'
```

**Comment by Bengoldacre** [comment]
hi all, 

i've asked jess f to chip in here. 

there are some discrepancies which are barndoor interesting and important, for example:
- trial status (completed in one register, ongoing in another) 

some discreps which where we find them are somewhat interesting for our pointy heads, eg:
- phase (if there are ever discreps on this)

some which are def uninteresting, eg:
- title text, summary text, between different languages (eg the mess that is EUCTR)

and then some in between.

can we in our next meet whizz thru a list of summary stats on discrepancies, ideally with redash open to check some examples, and hammer out some prioritisation on this that way?

**Comment by jessflem** [comment]
agreed with BenG above, potentially a three tier system (traffic lights):

trial status: red
target sample size, trail phase: amber
description (any long winded free text): green

EUCTR feels like the biggest barrier to any decent analysis on this right now.

**Comment by vitorbaptista** [comment]
@jessflem Interesting idea about the tier system. While we don't implement something like that, could you define a list of attributes from @roll's list at https://github.com/opentrials/opentrials/issues/234#issuecomment-234511442 where we should look for discrepancies in?

**Comment by jessflem** [comment]
@vitorbaptista the ones in bold are the ones I think we should look for discrepancies in:

'primary_register' 
'primary_id'
'identifiers'
'registration_date' 
'public_title'
'brief_summary'
'scientific_title'
'description'
**'recruitment_status'**
'eligibility_criteria'
**'target_sample_size'**
'first_enrollment_date'
'study_type'
'study_design'
**'study_phase'**
'primary_outcomes'
'secondary_outcomes'
**'gender'**
**'has_published_results'**

am I correct in thinking that we now have **'status'** as an attribute as well? because that one is SUPER interesting.

we still need to be able to see all the different titles etc, but maybe we shouldn't call them discrepancies. perhaps we call them versions? so you might have 5 different versions of the description? and in the same way that you can click on a link to see the discrepancies, you click on the description and it takes you through to a page like the discrepancies page but it shows you all the versions of the description side by side? similar to what we discussed with the outcome data in https://github.com/opentrials/opentrials/issues/334?
