### ISSUE TITLE
How to handle not existent identifiers from pubmed?

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#243]
For now if trial id from pubmed is not matched we create a stub trial in `trials` table. So if this will be useful (may be we just need to export this identifiers without stub trial creation) we need also to add stub records for this stub trials (esp. for https://github.com/opentrials/opentrials/issues/240).

**Comment by vitorbaptista** [comment]
At first I thought we should create a record in these cases, as it's no different from getting a trial from another of our sources. However, if we have records from pubmed for trials we didn't know about, shouldn't we have them for trials we know about as well? This would mean adding PubMed as a source for all trials, which is useless considering it only has the trial identifier.

Unless this is needed for other features, I'd be leaning towards not creating a record in this case.

**Comment by roll** [comment]
I've reformulated a question. For now we create stub `trial` for it (http://explorer.opentrials.net/trials/62d6ab9c-fe85-49f4-aadc-5bc600dedaef) - but may be we should just log it and report somehow? If we need this stub trials - do we need to create stub source for it?

**Comment by jessflem** [comment]
I don't think these stub trials are needed - ct.gov should be the source
for all nct numbers. Ideally, we would log it and then send the authors a
message saying 'hey numpties, this number is important and we can't find it
in ct.gov. check your spelling!' or report it through PubMed commons or
something. but I'd vote for scrapping the stub trials - since it looks like
they are just generated by spelling mistakes I can't imagine a good use for
them.

thanks!

**Comment by roll** [comment]
Thanks @jessflem! (cc @vitorbaptista)

**Comment by vitorbaptista** [comment]
So, we can't delete the pubmed-only trials from our database (as they're needed for research/stats), and there're too few to cause any issues. Let's leave things as is for now, then. I'm closing this issue, but feel free to reopen if needed.
