### ISSUE TITLE
Some identifiers from EUCTR are wrong

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#247]
For example, http://explorer.opentrials.net/trials/0aebad21-70e9-4b91-b2a8-9fc81a5fd253. Its primary identifier is EUCTR2015-005843-15**-3rd**, however it should be EUCTR2015-005843-15. The `-3rd` appears to come from the source URL (https://www.clinicaltrialsregister.eu/ctr-search/trial/2015-005843-15/3rd)

**Comment by vitorbaptista** [comment]
The same problem appers with country codes like `EUCTR2008-005767-34-FR`. The identifier shouldn't have `-FR` (as seen in the EudraCT number in https://www.clinicaltrialsregister.eu/ctr-search/trial/2008-005767-34/FR)

**Comment by roll** [comment]
All our euctr identifiers are like `EUCTR2008-005767-34-FR`.
It's how WHO ICTRP handle it. Because for different countries it's different trial instances (dates, number of participants etc).

So it's more deep problem (or may be not a problem). We alredy have a discrepancy issue for it - EUCTR2008-005767-34-FR

**Comment by roll** [comment]
So it's ongoing "question" from me (because I already have it - https://github.com/opentrials/opentrials/issues/221). And now not only me.

Really important to check by @opentrials/research team.

**Comment by roll** [comment]
It's fixed here - https://github.com/opentrials/processors/pull/39
