### ISSUE TITLE
What documents are contained in the "basic set" of documents we want for a trial?

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#265]
In our mockups at http://opentrials.github.io/mockups/trial.html we have:
![list of a trial's documents](https://cloud.githubusercontent.com/assets/76945/16955821/fb151946-4dcd-11e6-9f5d-f3f1dad88ea1.png)

There also appear to be a few more cited in figure 1 of the OpenTrials' paper at https://trialsjournal.biomedcentral.com/articles/10.1186/s13063-016-1290-8, but I'm not sure if that's the complete set. We need a list of the basic documents and their categories (regulatory, paperwork, ...) that **all** trials must have, sooner or later.

Just to be clear, there can be trials with documents not present in this basic set.

/cc @opentrials/research

**Comment by sarahcebm** [comment]
[The Guideline for Good Clinical Practice ](http://www.ich.org/fileadmin/Public_Web_Site/ICH_Products/Guidelines/Efficacy/E6/E6_R1_Guideline.pdf)contains a list of essential documents for the conduct of a clinical trial (Section 8). 

The list is quite lengthy and I realise that not all documents will count as a 'basic set' for our purposes. Beyond what is captured in the paper some of the key documents I think we should look at are:

**Regulatory**
Aggregate summaries of serious adverse events but not line listings due to patient confidentiality. 

**Paperwork**
Protocol AND amendments (may be in Papers category if it is published)
Agreements/contracts
Investigator's Brochure
Data Safety Monitoring Board (DSMB) charter (completed)
Evidence of Ethics/IRB approval

**Comment by vitorbaptista** [comment]
@sarahcebm Thanks for the quick reply! I have questions about a couple documents.

> **Regulatory**
> Aggregate summaries of serious adverse events but not line listings due to patient confidentiality. 

I imagine that this is only relevant to the trials that had serious adverse events? Or is it something we'd like for every trial?

> **Paperwork**
> Agreements/contracts

Is it about general agreements or contracts, or something specific?

**Comment by sarahcebm** [comment]
@vitorbaptista 

**Regulatory**:  This would apply to trials of devices and medicinal products. All trials in these categories should have an associated log of (serious) adverse events, both expected and unexpected, that occur during the conduct of the study. It is a requirement of ethics approval that they are reported back to the ethics committee. Usually they need to be aggregated, as individual events are fairly meaningless when trying to determine if they affect the study protocol, or indicate that one of the interventions being tested is harmful. 

**Paperwork** : Primarily I am thinking here of contracts between the sponsors/funders and the sites where the research is being conducted. They contain information like: financial arrangements, ownership of Intellectual property, control of results publication, insurance and indemnity etc. There may be others of interest such as those between collaborative groups of sites/researchers but I suspect they are less common.

**Comment by vitorbaptista** [comment]
Fixed
