### ISSUE TITLE
Where does the "Hello Kitty" intervention comes from?

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#291]
We have a few interventions that aren't related to any trial (e.g. http://explorer.opentrials.net/interventions/17124949-6b22-4e21-b0e8-41f229e0dc36). Where do they come from? How can we avoid this from happening in the future?

**Comment by roll** [comment]
Why we should avoid it?

It's from FDA Drug Labels - see redash with issue name - https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c929ecea-2001-433f-aa51-66a950bde734

So when we collect lookup tables for `conditions` and `interventions` there are subset of items not linked to trials but because it's lookup tables =) Just waiting for upcoming Hello Kitty trial :smile_cat:

**Comment by roll** [comment]
Also we some really useful info in `database` for professionals like ICDPCS_CODE and NDC_CODE. Also `database` has description for this interventions but UI doesn't show it.

**Comment by vitorbaptista** [comment]
@roll Having interventions (or other entities) without trials is quite surprising from a user perspective, specially because we're displaying them on the autocomplete field.

Because of this, I'd say that there shouldn't be any entity on OpenTrials that's not linked to a trial

**Comment by roll** [comment]
I really disagree on this. 

I don't think it's a way how data driven projects operates. We collect and normalize data using different strategies, time etc. Any good data for us is an asset which could be in use or used in a future.

For example we have full list of drug labels from the latest FDA issue. And we'going to delete 80% of this because **for now** there is no trials for it? But after processors improvement we could link more or we could have more trials later (for now our trials are outdated). Even for OpenTrialsFDA project we was talking about usage of this lookup table in the future. Really what a reason to delete this actual data?

Other example pubmed articles - we have 500k articles and only 30k linked. To delete 470k articles now? Why? After we will introduce new smart linkage methods we will find new related articles but we need those unlinked articles to match against something.

For me there is just an obvious solution - fix indexing script (I suppose it's enough) to remove confusing data from UI. But deleting good data sounds just wrong for me.

**Comment by vitorbaptista** [comment]
@roll I'm considering that all this data is available in the warehouse database, right? So we wouldn't be losing anything, just not adding information to our API database that's not used anywhere. Whenever we improve our processing steps and link more entities together, they'll appear in production.

We could change the indexing process not to index things that aren't linked to trials. This means that this data won't be searchable on OpenTrials, so the only way for someone to access them is by knowing their IDs. In practical terms, this means that we'll have data in our API database that's not used anywhere. Why keep it there, then?

**Comment by roll** [comment]
@vitorbaptista 
But `warehouse` data is not suitable to work with it because it's not normalized (own format for every source). So `database` here is to provide this normalized data to work with.

**Comment by vitorbaptista** [comment]
@roll I feel like I'm missing something. Please, confirm the following:

* With the current collectors/processors architecture, we could delete our whole production database at any time and recreate it simply by re-running the processors, with no need to scrape the sources again.
* The matching done by the processors work on the warehouse database only, so removing data from the API database shouldn't have any effect on them.

Is it true?

**Comment by roll** [comment]
@vitorbaptista 
Commenting two sentences:

1. It's true.

2. It's totally opposite to reality. All matching, linking etc queries are issued against `database` not `warehouse`. Consider we process some trial:
  - from trial source data we have extracted `superdrug` intervention
  - we query `database.interventions` to find a match. We don't query `warehouse.fdadl` for `name` field, `warehouse.icdpcs` for `icd_title` field (naming is not the same) and other from the future we even have no idea about. Because we already have a lookup table `database.interventions` to work with merged and normalized data with `name` filed .
The same for `pubmed_linker` - works exclusively on `database` level. And even all trial deduplication queries are against `database.trials` table not 10 `warehouse.xxx` tables. There is just no other way to work with unnormalized data from many different sources.

**Comment by vitorbaptista** [comment]
@roll OK, that was my misunderstanding. That being the case, I agree that this issue should be solved in the indexing level. I created issue https://github.com/opentrials/opentrials/issues/301 to track this task. Closing this for now.
