### ISSUE TITLE
Improve the UI of the search results page?

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#305]
Here is our search results page: http://explorer.opentrials.net/search

Comparing to other sites:
- https://mytomorrows.com/en/conditions/580/adenocarcinoma/trials/page/1/?country=RU&gender&intervention&sortBy=alphabetical_order
- http://www.takedaclinicaltrials.com/browse/?sub_conditions=&compound=&country=&age=&search_terms=cancer&protocol_id=&nct_id=&study_type=
- http://www.pfizer.com/research/clinical_trials/find_a_trial?group[cancer]=1&condition[cancer]=cancer&recr=1
- http://apps.who.int/trialsearch/Default.aspx
- etc

I should say ours is not looking as a leader. For example critical information like `recruitment_status` is missing. I think we need to invest some time into it before the launch (we even have things like `Internetions: <blank line>`)

**Comment by nightsh** [comment]
My 2 cents on the issue:

We're not far from having a much better search page. The current structure allows for a nicer presentation without having to modify much of it. I personally liked takedaclinicaltrials the most.

Some ideas to start with:

* find a way to add more data to the results previews without bloating the UI (icons with tooltips?)
* a friendlier (maybe with a smaller footprint)  "refine search results" thingy would probably be nice
* visually (and discretely) isolate the search results, either by a small separator, (alternate?) backgrounds or something else
* whatever we do, I'd avoid using colors and/or color codes. Just look [at this page](http://www.takedaclinicaltrials.com/browse/?sub_conditions=&compound=&country=&age=&search_terms=rectal+cancer&protocol_id=&nct_id=&study_type=) and see how crowded it looks

**Comment by smth** [comment]
As part of this I'd  like to take a look at how we present the "advanced" fields, as mentioned here https://github.com/opentrials/opentrials/issues/347

**Comment by smth** [comment]
Here's a mockup with the "advanced" filters moved into this page, amongst some smaller tweaks. Would this resolve the concerns here?

![opentrials_08_search_01](https://cloud.githubusercontent.com/assets/1375708/18275597/9f34f9dc-743f-11e6-9a4c-75b54b8a54b1.jpg)

**Comment by vitorbaptista** [comment]
@smth Looks great! A few comments:

I'm not sure about changing the dropdowns (e.g. Gender and Study results) for checkboxes, as we require at least one of the values to be selected (i.e. there're no trials with no male nor female participants). I don't know if checkboxes are the best fit here, so I would either keep them as dropdowns or use radio buttons (e.g. `All`, `Male participants`, `Female participants`).

I noticed that you removed the search/clear buttons. I imagine that's because you're thinking the search results would automatically update whenever we change the filters. That'd be great, but we're not ready for it yet, so we still need the buttons.

I also like the slider for sample size and the `x` button to remove specific filters (if I get them right).

Overall, this is a great improvement from what we have :clap::clap::clap:

**Comment by nightsh** [comment]
This. Is. Great!! @smth, you rock :metal: 

I have no comments other than supporting what @vitorbaptista said.

Now, somebody has to step up and work some markup 😬 
(I can do it, but I can only start in about a week's time or so, I'm trying to close other issues in the meantime)

**Comment by pwalsh** [comment]
@nightsh @smth is skilled at markup :)

**Comment by nightsh** [comment]
Awesome, I had no idea! Just the new dude being awkward 😁 

Cheers, @smth, for proving heroes do exist!

**Comment by smth** [comment]
Thanks for the feedback, all good points. I'll step up today ;)

**Comment by vitorbaptista** [comment]
Merged @smth's excellent work. There are a few issues still, but nothing to block merging. I created issues #404, #405, #406 and #407 to track them.
