### ISSUE TITLE
Define scope for working with Cochrane schizophrenia data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#308]
# Description

**After** https://github.com/opentrials/opentrials/issues/307 we need to lock down on a scope of work for the short term (before Sept. 1st) that will help achieve some immediate goals ( defined by @jessflem ), and be relatively straight forward in terms of integration with the main OpenTrials database.

# Tasks

- [x] Work directly with @jessflem (over 1-2 calls perhaps) to understand the immediate goals and make a high-level plan for action
- [x] Then, work out the basic technical details of this, and sync with @roll on 
  - the soundness of the scope (are there any possible complications)
  - the usage of opentrials [processors](https://github.com/opentrials/processors) and [collectors](https://github.com/opentrials/collectors) to achieve this

**Comment by georgiana-b** [comment]
The potentially useful information from `.rm5` files [has been extracted and analyzed here](https://github.com/georgiana-b/cochrane-data). 

Context: 
A reviewer selects several trials on a certain subject. For each trial, based on the analysis of its publications, reviewers assess the risk of different biases. 
The trials have an id like "STD-Carpenter-1999" but I couldn't find a correspondent for it outside this data. Besides that, the trials can be identified based on the publications analyzed in the reviews. Reviewers provide basic info about publications (i.e. `title`, `authors`, `type`) and sometimes identifiers from their sources (ex. PubMed ID).

Strategy: 

1. Keep the reviews we have so far in a place where they can be easily retrieved from and added to if necessary.
2. Make a collector that parses each review and adds a row with the results of each trial to a `warehouse` table .
3. Make a processor that grabs all results of a trial from the `warehouse` table and tries to match at least one of it's publications with a publication from `opentrials`.
4.  If no match is found, try to find a match with other publications in `warehouse`.  Use the matched publication's `source_url` to find it's counterpart in `opentrials` database.

      This is quite cumbersome but since many publication attributes get lost in transition from `warehouse` to `opentrials`, matching against `warehouse` increases the changes of finding something.
5. Use the publication to connect the review trial to the `opentrials` trial. Add the review to a `reviews` table in `opentrials` and a reference to its corresponding trial.

       This assumes each publication can be uniquely liked to a trial which I'm not so sure of given the [many-to-many relationship between them](https://github.com/opentrials/api/blob/master/api/models/trial.js#L99).

**Comment by roll** [comment]
@nightsh 
Adding `pubmed_id` to `database.publications` could take like around 1 hour but it will really simplify things to @georgiana-b

**Comment by roll** [comment]
@georgiana-b 
Collector should be a straight forward - you need just write every source data field as `warehouse.cochrane` field.

Second part also requires to add `database.reviews` table or add `database.publications.type` enum. I suppose @vitorbaptista will handle this. Also because HRA data is waiting it.

**Comment by vitorbaptista** [comment]
@georgiana-b Could you expand on what data schema you're thinking for the OpenTrials side? Is it a simple table with columns for each of the risk of bias analysis criteria (e.g. `double_blind`, etc.)?

**Comment by georgiana-b** [comment]
@vitorbaptista Practically a `review` should have a many-to-many relationship with a `trial` though `review-results` that would contain a reference to the review, a reference to a trial and the actual results.
However, since we are not so interested in the `review` or to query from the `review` side, I'm thinking we could have a table called `review-results`(or around those lines) that keeps in each row the results of a trial in a certain review. So, a `trial` has many `review-results` witch  a schema like: 

**ReviewResults** 
id 
trial_id
review_url/review_file_name 
criteria1 
criteria2 
etc.

**Comment by vitorbaptista** [comment]
@georgiana-b Sounds good. And do we have a base structure for the criteria used?

**Comment by nightsh** [comment]
what if we do a `criteria` field with a JSON content? I'm not familiar with the data content, just asking based on the proposed structure.

```json
[
    {"name": "criteria1", "value": "something"},
    {"name": "criteria2", "value": "some other thing"}
]
```

**Comment by georgiana-b** [comment]
@vitorbaptista: @jessflem was kind to map the criteria to the text we are supposed to display [here](https://docs.google.com/document/d/1VUlPR4OTRYue0tuARWbkLN6dW00FxRuDNAhiG9r-EE8/edit?usp=sharing). The important bit for schema is this table:

| ROB ID in the reviews | ROB natural language name |
|----------|:-------------:|
| 1 |  "sequence generation" | 
| 2 |   "allocation concealment"  |
| 3 | "blinding (performance and/or detection)" |
| 3.1 | "blinding (performance)" |
| 3.2 | "blinding (detection)" |
| 4 | "attrition" |
| 5 | "reporting" |
| 6 | "other biases" |

So, since we have (at least) 3 as an outlier,  I think the best way would be to keep them as JSON in a `results` field as @nightsh mentioned. 
If it's easier to work with them, we could split 3 in 3.1 and 3.2 all the time and store them as normal columns. @jessflem, would that be accurate or there is no way to know if it's an "and" or an "or"?
Also, @nightsh and other people who have to work with them, feel free to express your preference.

**Comment by nightsh** [comment]
I still believe keeping the ROBs as JSON in one of the review's columns would be  a good idea, so this is my vote :neckbeard:

**Comment by roll** [comment]
We also have this - https://github.com/opentrials/opentrials/issues/242

**Comment by jessflem** [comment]
@georgiana-b there is no way to know (without potentially manually going through the free text) how to break 3 into 3.1 and 3.2. If needed, 3.1 and 3.2 could be combined for those with both, and the worst score assigned to 3 instead (so if low risk of bias in 3.1 and high risk of bias in 3.2 then assign high risk of bias to 3). does that make sense?

**Comment by georgiana-b** [comment]
@jessflem Yes, thank you! That is a strong argument in favor of JSON.

**Comment by roll** [comment]
@vitorbaptista 
It looks like we again design schema earlier than understanding how we going to use it.

**Comment by georgiana-b** [comment]
@roll That was my point also. I just presented the facts.You certainly know more about the details behind the `opentrials` database architecture and usage than me. So how do you think the schema should like?

**Comment by roll** [comment]
@georgiana-b 
I suppose it's question only for @jessflem - what and where we need to show on http://explorer.opentrials.net/ related to this data? 

Then we need to stub explorer page for it and api endpoint -> migration -> processor. In my opinion dev should be like this. Because we already have a really bit experience here of modelling some abastract data and then updating and updating schema to meet **real** client requirements.

**Comment by jessflem** [comment]
I've provided @georgiana-b with the free text that we want to generate from this data, and we would like it to look like the 'methodological rigour' section in the original mock up:

![image](https://cloud.githubusercontent.com/assets/10628540/18139599/1b30270e-6faa-11e6-8f0b-8f97e16c981a.png)

**Comment by georgiana-b** [comment]
After a discussion with @vitorbaptista, this new schema was born:

**Risk of Bias**
id
trial_id
source_id
url

**Risk of Bias -> Risk of Bias Criteria**
risk_of_bias_id
risk_of_bias_criteria_id
value

**Risk of Bias Criteria**
id
name

Feel free to point out any issues/improvements.

**Comment by vitorbaptista** [comment]
Done
