### ISSUE TITLE
Do we need primary/secondary_outcomes as trial attributes

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#334]
# Overview

For now we have this two trial attributes:
- `primary_outcomes`
- `secondary_outcomes`

Contents of this fields is really not regular between different sources (the more frequently it's object/nested mapping without any unified for OT structure). Show this data could be ugly and extract some normalized data from this fields could be problematic.

So question - do we need it at all in main database (this data is reproducible and we store it in `warehouse` anyway)?

PS.
There is only one other complex trial attribute `eligibility_criteria` (also not normalized object/nested mapping) but I suppose we could do something with it because of this information importance. But please comment this also - do we need to show it on trial details page for example? If not we could remove it too.

@opentrials/research

**Comment by jessflem** [comment]
@roll 

primary and secondary outcomes are important but I agree, the data is super messy. rather than have the free text on the main trial page would it be possible to have the following:

a link on the main page to a primary and secondary outcomes page
a separate 'outcomes' page that provides the outcomes (as free text) from each of the different registers, side by side

this would enable a researcher to compare between the two registers and pick up on any suspicious discrepancies between the two, even if we aren't able to formally flag them up.

would that be possible?

**Comment by roll** [comment]
@jessflem 
Thanks, I suppose we will be able to implement it later.

So we need this fields for the next stages of the project
