### ISSUE TITLE
Deploy Airflow to our infrastructure

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#523]
We have an Airflow configuration working with Docker Compose on https://github.com/opentrials/opentrials-airflow. However, as our infra uses Kubernetes, that'll need to be converted.

@pwalsh Do you think this is something the infra team can help with? It would be useful to have it, specially with the new guys from LabAnalytics coming to work with the data.

**Comment by pwalsh** [comment]
@vitorbaptista yes, they will do it. I'll try to get it done this week.

**Comment by vitorbaptista** [comment]
It would also be great if our deployment infrastructure could automatically re-deploy when a new Docker image is pushed to https://hub.docker.com/r/okibot/opentrials-airflow/. I think that won't mess up with currently running tasks, as their state is synchronized by the underlying Celery/Postgres.

**Comment by pwalsh** [comment]
@vitorbaptista that would be good. To do it, we have to have a strongly enforced convention where we only ever push to docker hub when we are 100% ready to deploy

**Comment by vitorbaptista** [comment]
@pwalsh Yeah, for that we would need a staging environment and some tests (which are very difficult to write with Airflow, we can at most do basic smoke ones like "does this run?"). Thinking better now, as long as it's a one-click deployment, let's leave it at that. We can improve when/if we end up with a staging environment where we can be safer.

**Comment by pwalsh** [comment]
yeah. on my own little dock setup, which is like cubes or deis in miniature, I started on something similar, and just decided it was quick and safer to run a bash script manually for each actual deployment. Let's see.

**Comment by vitorbaptista** [comment]
@nightsh Please close this whenever you can run any DAG on our deployed Airflow

**Comment by nightsh** [comment]
I've done a bit of pair work & debugging with Marko on this. Here are some updates:

* Airflow was successfully deployed
* Had an issue with the worker container, fixed it (it was due to the way Kubernetes injects env vars into pods, in this case conflicting with of Airflow's)
* Had another issue with the logs not being accessible by the web server, fixed by fixing some host names definitions.
* Next was Airflow not being able to run Docker containers (required a privileged pod), which was fixed by escalating the privileges inside the worker container to be able to operate on the mounted Docker socket
  * Had to create a separate `opentrials-airflow-worker` image for it, see it [on Docker Hub](https://hub.docker.com/r/okibot/opentrials-airflow-worker/)
* Next issue to be tackled (I hope the last one) is that Fernet raises a Invalid Token error.

So, as of today, we can:

* create DAGs and run them
* run `DockerOperator` tasks
* see the logs
* schedule DAGs, edit variables, connections etc.

Seems like we're one step from an end-to-end trial.

Other near future tasks (for which I'll create separate issues):

* avoid rebuilding the container just to see the new DAGs
  * Kubernetes seems to be able to mount a GitHub volume, so we can probably mount the repo and have the new DAGs copied into `AIRFLOW_HOME` at startup
  * ideally, we would just reboot a container to see the DAGs pushed to `master` branch of [opentrials-airflow](https://github.com/opentrials/opentrials-airflow)
* set up automated builds for the worker container too
* reorganize the repository to reflect the latest deveopments (some cleanup is in order)
* the two images we build (airflow and worker) only differ by one `Dockerfile` line, would be great to create them based on the same file (I'm thinking env vars, build time params, stuff like this)

Will update as soon as we manage to move this forward.

**Comment by nightsh** [comment]
Updating here, just to keep a log of what happens.

* Fixed FERNET_KEY issue, I missed its export into DAG tasks containers
* New issue, docker py lib complains about having a superior version than the server's, thus refusing to run anything, raising this: `ERROR - 400 Client Error: Bad Request ("client is newer than server (client API version: 1.24, server API version: 1.23)")`. Fix is in progress.

**Comment by vitorbaptista** [comment]
@nightsh Any updates here?

**Comment by vitorbaptista** [comment]
Done
