### ISSUE TITLE
Some data on Drugs@FDA is not available on OpenTrialsFDA

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#587]
# Description

Some drugs on Drugs@FDA is not available on OpenTrialsFDA do not turn up on OpenTrialsFDA. We received the following report:

    There’s this drug called Myrbetriq (mirabegron) [brand name (generic name)] that I found in Drugs@FDA but I cannot find in OTFDA. I tried both the regular search field and the ones under Advanced Search. It apparently was posted in Aug 2012, so we can’t blame it on its being added after our mass download.

# Tasks

- [ ] TBD

**Comment by vitorbaptista** [comment]
I did some quick tests and it was apparently caused by a bug on the `processor/base/writers/file.py` writer. We used a pattern like:

```python
foo = data.get(''foo', default_data['foo'))
```

Because I thought `default_data['foo']` would only be executed if `data['foo']` didn't exist. That isn't true, so we changed that on https://github.com/opentrials/processors/blob/7680917422c5a4f5e2efd26cc3cb07691c844878/processors/base/writers/file.py#L43-L44. If I'm correct, this will be fixed when we re-run our FDA processors.

**Comment by nightsh** [comment]
Will start the FDA processors tomorrow, to have them running over the weekend. Self assigning so I won't forget.

**Comment by georgiana-b** [comment]
The FDA processor has been run again after the above mentioned fix and now [the drug is available in OpenTrials](https://explorer.opentrials.net/search?q=&intervention=Myrbetriq&sample_size_start=&sample_size_end=&gender=&has_published_results=&has_publications=&has_discrepancies=&registration_date_start=&registration_date_end=). Looks like this was solved so I'll close it.

**Comment by georgiana-b** [comment]
The bug has probably been solved by the above mentioned fix in `processor/base/writers/file.py`  because it [is available in OpenTrials now](https://explorer.opentrials.net/search?q=&intervention=Myrbetriq&sample_size_start=&sample_size_end=&gender=&has_published_results=&has_publications=&has_discrepancies=&registration_date_start=&registration_date_end=) but the FDA processors and indexer need to be run to confirm the fix.

**Comment by vitorbaptista** [comment]
Myrbetriq isn't in our FDA database, it's just part of the FDA Drug Labels import that we've done, but [you can't find it via OpenTrialsFDA](https://fda.opentrials.net/search?q=Myrbetriq). This is blocked waiting for the FDA collectors/processors to be re-run, which might require rewriting the collector, as the FDA website changed.

**Comment by pwalsh** [comment]
WONTFIX until phase II
