### ISSUE TITLE
Dynamic search options based on other selected options

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#588]
# Description

When searching, one can do a free text search, and then on the results page, further refine the search. However, the refinement options include all possibilities for that refinement data set, and are not in themselves filtered by the existing search query. This likely has performance implications (we could search over less data in such scenarios), but most importantly, it can lead to a surprising user experience.

Here is a report from a user:

    When I did a search for brexpiprazole you have a great option to restrict by condition (I like the idea of this and may see if I can add it to Trip) but it seems to be a list of ALL conditions in your system.  It would make more sense to just show the conditions which actually have been trialled with brexpiprazole.

# Tasks

- [ ] TBD

**Comment by nightsh** [comment]
This would probably slow down the user experience overall. Imagine we're doing it and every time you select something, a new request is being made to narrow down the other fields. This usually is not a problem, but we have many such fields...

I have another concern to raise. Imagine the following user story:

* as a user, I access the search UI
* I select from the suggested items one person and an organization
* for all the other autocomplete fields, I only see the applicable values to my existing query (i.e. chosen person + organization)
* I scroll down to the static dropdowns, I see "Publications" and I choose "Trials with publications"
* I get no results, since there are only trials without results on the query I made. But that field [was statically built into the template](https://github.com/opentrials/opentrials/blob/master/views/partials/search-form-fields.html#L77-L91).

My point is, if we do this, we must start by making all the fields adjustable. This would have the nice side effect that we will have very few empty results (or none).

Does it make sense? @vitorbaptista, any thoughts on this?

**Comment by vitorbaptista** [comment]
We're disabling the autocomplete feature (#651), because it isn't useful with the messy data we have. So, this feature won't be relevant anymore. We can revisit it whenever we have data clean enough to re-enable autocomplete.
