### ISSUE TITLE
Extract and expose last verified date from NCT

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#594]
For example, on https://clinicaltrials.gov/ct2/show/NCT00564096:

![transcranial magnetic stimulation tms in schizophrenia - full text view - clinicaltrials gov](https://cloud.githubusercontent.com/assets/76945/20916912/1911e258-bb97-11e6-8d10-88fb24d3c68c.png)

See https://github.com/opentrials/opentrials/issues/515 for more information on this issue.

**Comment by georgiana-b** [comment]
In #515, me and @jessflem have determined that GSK also has the `last_validated` information. After a discussion you can read there, we concluded that:
1. `last_verified` should only be a property of `record` (not of `trial`)
2. the value we display for `last_verified` should be from the same `record` from which we took the `status` (i.e. primary record)

We already have in Processors [logic for determining which `record` is the primary source of data](https://github.com/opentrials/processors/blob/master/processors/base/writers/trial.py#L47) (i.e. from which `record` we take the values for a `trial`). However, that information is not stored anywhere so we can't decide which `last_verified` to display because we don't know from which `record` was the `status` taken.
This is problem also applies to trials that have multiple records from the same source [like this one that has 3 records from NCT](https://explorer.opentrials.net/trials/c4643df6-8bd4-11e6-a449-0242ac12000b).

Ways to go:
* store which `record` is primary
* don't display `last_verified`

@pwalsh, @jessflem What do you think?

**Comment by pwalsh** [comment]
Store which record is primary

**Comment by georgiana-b** [comment]
Closed via opentrials/processors#96, opentrials/api#132 and opentrials/opentrials#615

**Comment by vitorbaptista** [comment]
@georgiana-b I asked this in another issue, but maybe it's best to keep the discussion here. Why don't we add `last_verified` to the `trials` table as well? I didn't understand why it's different than any other field we have.
