### ISSUE TITLE
Data contribution categories mapping to trial page 'Documents' items

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#613]
On a particular trial page, there are the following 'Documents' items:

* Blank case report form
* Blank consent form
* Patient information sheet
* Clinical study report
* Clinical study report synopsis
* EPAR Segment
* Results

If a user contributes an item without a corresponding 'Documents' item (e.g. Analytics Code or a link/URL) once approved by the OpenTrials research team, where will it appear on the trial page?

Also, related to this - we need to display attribution information (#316) on a trial page for user contributed items.

**Comment by pwalsh** [comment]
The documents need to go through a manual mapping process. The data provided by the user helps with this, but it does not trigger a fully automated flow (yet).

So, the answer it: it will go to the location it is explicitly mapped to, by the programmer who takes the data contribution and builds the `processor` to get it into the database.

@benmeg do we need to do something here, or is the answer enough?

**Comment by benmeg** [comment]
I think it's fine for now, but we may need to discuss once we've added documents which don't fall under the above list.

One solution would be to have a red/green box for every type of document (from the data contributions drop-down) under the 'Documents' section of each trial page. But given the number (currently 19, minus a few which have a different place on a trial page e.g. Publications) adding that many boxes may look crowded/messy.

**Comment by nightsh** [comment]
@benmeg @pwalsh 
I have quite a bunch of thoughts about this, why won't we have a quick chat about data contributions (the whole process: submissions, curation, further integration within our DB) after holidays? We can probably draft some ideas in existing/new issues and give us some sense of direction about it.

I'm going to close this issue, since it's not actionable right now. Might be a task from the future, but currently it lacks the infrastructure to build on.
