### ISSUE TITLE
Process new data contributions

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#628]
@georgiana-b @nightsh this is quite urgent, especially the Ebola-related contributions.

**Comment by georgiana-b** [comment]
@opentrials/research According to this task, we are going to transform data contributions into their corresponding entities in `opentrials` API database  ( `publications`, `documents` etc. ). In order to do this we need a mapping of data contribution categories to database entity and type.

I made [a spreadsheet here](https://docs.google.com/spreadsheets/d/1mNtceWbp_eoP9HrFkHiSF1AFvemJNK4Th4xS69qGOa4/edit?usp=sharing) with current data contribution categories. I mapped a few of them to the API database just for reference (maybe incorrectly, feel free to update). Please supply mapping for the other categories that should go into the API database.

For table `documents` we currently have a field `type` that can have only 3 values now: `csr_synopsis`, `other` and `results`. We will add other types requested in the mapping.

**Comment by sarahcebm** [comment]
Hi @georgiana-b. Can I see the current listings for all entities so I can understand how it is currently mapped? The document field types you list don't match those on the trial entry e.g paperwork/regulatory documents/data. Also, is there a rationale for the current mappings that I can read?

**Comment by georgiana-b** [comment]
@sarahcebm 

> Can I see the current listings for all entities so I can understand how it is currently mapped? 

Right now there is no mapping of data contributions to our `opentrials` database schema because we didn't process them so far. That's what we have to solve now.

> The document field types you list don't match those on the trial entry e.g paperwork/regulatory documents/data.

The more general categories you mentioned are [used to display the documents more conveniently](https://github.com/opentrials/opentrials/blob/master/presenters/trial.js#L6). We could get rid of those in the future since they require yet another mapping to maintain.
I was referring to the [types of documents we have in the database](https://query.opentrials.net/queries/194). For convenience, here is a list with all document types we allow at the moment and the category used for displaying them:

| database document type | display document type |
|----|----|
| blank_consent_form | Paperwork |
| patient_information_sheet | Paperwork |
| blank_case_report_form | Paperwork|
| csr | Regulatory documents |
| csr_synopsis | Regulatory documents |
| epar_segment | Regulatory documents |
| results | Data |

So, the mapping in the spreadsheet should be to `opentrials` database entities that you can [explore in Redash](https://query.opentrials.net/queries/new), mainly [`documents`](https://query.opentrials.net/queries/195/) with the types mentioned above in "database document type". Do not feel constrained by the existing types though because we can add more/change them if needed.

**Comment by georgiana-b** [comment]
@sarahcebm After writing the comment above I noticed your `data_categories` already include all the existing `database document types` and any more to come so it's better to replace that `document type` with your `data categories`. We're discussing that possibility now so don't waste time on this for now. We'll let you know if it will still be needed.

**Comment by sarahcebm** [comment]
Ok, thanks @georgiana-b. I was thinking along these lines i.e that we should reconcile the data contributions mapping and the document display categories. Let me know if you need my input.

**Comment by georgiana-b** [comment]
@sarahcebm We've settled on replacing the `document type` with your `data_categories` so no mapping will be needed. 
I was also thinking we should replace the "display document types" (e.g. "Paperwork") with the `group` attribute in your `data_categories`. What do you think?

**Comment by sarahcebm** [comment]
@georgiana-b great. When reviewing data contributions with @bengoldacre, we found that another sub-category was needed under Miscellaneous group. We have added 'Journal article, secondary or independent re-analysis of results' to original list[ here.] Can you please ensure this is updated on your side. Relates to https://github.com/opentrials/opentrials/issues/558  Thanks! (https://docs.google.com/document/d/1oqJ95uVCzT-u9vy4SK8qK_U-osRnlzVUULf4Q3qzSwc/edit)

How would replacing "display document types" impact on the current display for individual entries? It seems sensible to be consistent across the mappings, but not sure we want all possible submission types (unless every item is in fact available), as will be quite crowded visually etc.

**Comment by georgiana-b** [comment]
@sarahcebm I'll make sure to add that new sub-category.  
As for replacing `display document types`, I'll make the changes and upload a picture so you'll be able to take a look and decide if we should apply the change to the website.

**Comment by benmeg** [comment]
Was just going through some old emails - @Bengoldacre had said it would be nice to add 'Investigator Brochure' (which I see in the spreadsheet) and 'Recruitment Poster' (which isn't there yet) as non-obligatory document types.

**Comment by vitorbaptista** [comment]
The code is live. We process data contributions daily, adding approved data contributions and removing rejected ones. They just need a valid trial ID and a valid category, which you can change via the admin page. There's a known issue with links behind a paywall documented on https://github.com/opentrials/opentrials/issues/702, but it is a quick fix.

I'll write an e-mail later explaining the data curation process.

Thanks @georgiana-b for all the hard work you've poured into this :clap:
