### ISSUE TITLE
Fields that are not included in mapping are indexed in ElasticSearch anyway

### ISSUE THREAD

**Issue by georgiana-b** [opentrials/opentrials#647]
Currently we don't include `status` and `risks_of_bias` in [our mapping for the `trial` ElasticSearch index](https://github.com/opentrials/api/blob/master/tools/indexers/trials.js).

 However, these fields and any other field returned by 
```
new Trial({ id }).fetch({ withRelated: Trial.relatedModels })
```
are indexed anyway. [Here is the response](https://gist.github.com/georgiana-b/1dc6fae5216b64fcca813930767e55af) returned by 

```
$ curl localhost:9200/trials_2017-01-21_1485004350175/trial/_search?pretty
```
on a fresh index.

[Here is](https://gist.github.com/georgiana-b/3b67eba325341acd3ce53e7f33f1d219) the mapping of the `trial` index as returned by 

```
$ curl localhost:9200/trials_trials_2017-01-21_1485004350175/trial/_mapping?pretty
```

As you can see there,  `risks_of_bias`, `sources`, `status` etc. have been dynamically mapped (not always correctly). 

I looked through the code but I couldn't find anything that would suggest this behaviour is intended, so I'll assume this is a bug.

**Comment by nightsh** [comment]
A few updates on this:

To stop the extra fields being added, [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html) says:
> The automatic detection and addition of new types and fields is called dynamic mapping. 
> [...]
> Automatic type creation can be disabled per-index by setting the index.mapper.dynamic setting to false in the index settings.

I applied this setting in our `trials.js` indexer – it went through (I was able to see the setting in the index properties afterwards) – and the extra fields kept being added:

```javascript
module.exports = {
  index: {
    body: {
      settings: {
        "index.mapper.dynamic": false,
      },
      mappings: {
        trial: trialMapping,
      },
    },
  },
```

However, if I define it in the mapping itself, rather than in the index settings, it works. Just put this on the same level as `trialMapping.properties`: 
```javascript
  dynamic: false,
```

After briefly discussing the issue with @vitorbaptista, we agreed the extra fields don't really bother us, but it would be nice to explicitly declare them in the mapping. Therefore, we could:

* set `dynamic: 'strict'` in the mapping(s), so it would throw an error if being passed unknown things
* manually declare the missing properties in the mapping
* write a couple of tests for it

That won't really add any new feature or modify the user level experience at all. Being more of a housekeeping task to do, I'm slapping a "tech debt" label on it.
