### ISSUE TITLE
Create trial entity for unregistered trials from PubMed

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#656]
Unregistered trials are defined on #655. Populate the fields:

* Title -> publication's title
* Summary -> publication's abstract
* Publications -> the publication itself

They should have some UI element to differentiate them in the search results from the other registered trials, and potentially remove things that they'll never have like `conditions` and `interventions`

**Comment by georgiana-b** [comment]
@vitorbaptista I have some questions regarding unregistered trials.

Context: Currently [we extract `trial` identifiers from `publications` `title` and `abstract` attributes](https://github.com/opentrials/processors/blob/master/processors/pubmed_linker/processor.py#L23). This is a very loose linking since it doesn't guarantee that a `trial` reference means the `publication` is a byproduct of that `trial` (people could reference a `trial` in the `abstract` for all sorts of reasons). We have a way to make this process more specific that I described in #682.

Having these said, here are the questions:
1. We consider a `publication` to be an unregistered `trial`:
   a. if it doesn't have any references to `trials` in our database
   b. if it doesn't have identifiers that suggest it belongs to a `trial` registered in other sources (i.e. no values in `DataBankList`(see #682)

2. If an "unregistered" `trial` has been created from a `publication`, do we update the attributes of the `trial` every time the `publication` is updated?

3. If a `publication` is updated with identifiers (e.g. NCT ID is added to `DataBankList`) we can conclude that the unregistered `trial` created from it is no longer unregistered and delete it? 
Even if we don't have a `trial` with that NCT ID in our database?

**Comment by vitorbaptista** [comment]
> 1. We consider a `publication` to be an unregistered `trial`:
>    a. if it doesn't have any references to `trials` in our database
>    b. if it doesn't have identifiers that suggest it belongs to a `trial` registered in other sources (i.e. no values in `DataBankList`(see #682)

Sounds sensible

> 2. If an "unregistered" `trial` has been created from a `publication`, do we update the attributes of the `trial` every time the `publication` is updated?

Yes

> 3. If a `publication` is updated with identifiers (e.g. NCT ID is added to `DataBankList`) we can conclude that the unregistered `trial` created from it is no longer unregistered and delete it?  
> Even if we don't have a `trial` with that NCT ID in our database?

Our assumptions are that we would get any registered trial from our other sources (nct, euctr, ...). So, let's consider a case where a trial was created with `source_id == 'pubmed'`, and then they add a identifier to its XML file. Next time the `pubmed` processor ran, it would:

1. Add the new identifiers to the `trial.identifiers`

Then, some time later, some other processor ran (e.g. `nct`), and then:

1. If it has the same identifiers as the `pubmed` trial, it would overwrite the trial on `trials` table
2. As we use the `DataBank` to create links between trials and publications, we would link the PubMed's publication to this newly created trial.

In the end, the data in our DB would be correct with only one trial `source_id == 'nct'` and the publication linked in the `trials_publications` relationship table.

For this to work, we must not only create `trials` with `source_id == 'pubmed'` but also `records`, so we keep the invariant that "every trial has at least one record". We would have to remove those `records` when this happens as well. As in having a processor that would remove any `records` where `records.source_id == 'pubmed'` and the trial has other records from other sources.

What do you think?

**Comment by georgiana-b** [comment]
> We consider a publication to be an unregistered trial:
a. if it doesn't have any references to trials in our database
b. if it doesn't have identifiers that suggest it belongs to a trial registered in other sources (i.e. no values in DataBankList(see #682)

After further analysis and development, I concluded that option `a.  if it doesn't have any references to trials in our database` is not a safe way to decide if a trial is unregistered. Here are my reasons:
* It seems sensible to conclude that if a publication contains trial identifiers, that trial is registered. If we don't find a `trial` for a PubMed publication that contains in it's `DataBankList` a valid identifier it's probably because we didn't scrape that `trial` yet from it's source.
* There are PubMed publications that contain results for multiple `trials`. For example, [this publication](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi/?db=pubmed&id=22327499&retmode=xml) has multiple NCT identifiers. If we don't find any of the `trials` in the database we should create 2 trials from this `publication` but we can't have 2 trials with the same `source_url`.

Therefore, we will create unregistered `trials` only from the publications that don't have any trial identifiers in their `DataBankList`.
If the publications are updated with trial identifiers in their `DataBankList`, we will remove the unregistered trials created from them.

@jessflem @sarahcebm The strategy I described above seems fine from a technical perspective. However, this issue involves domain knowledge that I don't have. I would greatly appreciate if you shared your opinion.

**Comment by vitorbaptista** [comment]
@georgiana-b This is just missing the UI changes on the Explorer. There wasn't any requirements written on what we need to do with unregistered trials on the UI, so it would be great if you could think about it and write a quick proposal here. The main issues are handling trials that have mostly no metadata in, specially in the search results (the trial details page is OK-ish IMHO). Maybe we could expose the main source in the results, and so those trials would appear as from PubMed (we shouldn't call them "unregistered trials")?

**Comment by georgiana-b** [comment]
After trying out several options, here are the main ones: 

Add source name and show metadata for unregistered trials - seems repetitive because they all have the same values:
![unregistered_trials_with_overview](https://cloud.githubusercontent.com/assets/8862002/24804911/a69a774e-1bb8-11e7-9cba-8befaaaf5750.png)

Unregistered trials only with title and summary - looks duller but at least it's makes the unregistered trials more obvious so I'd go with this one: 
![unregistered_trials_no_empty_fields](https://cloud.githubusercontent.com/assets/8862002/24804231/7306d014-1bb6-11e7-962a-64e8e50a3e48.png)

@vitorbaptista What do you think?

**Comment by georgiana-b** [comment]
Here is the trial details view for an unregistered trial. I think it doesn't need any changes but feel free to bring suggestions if you disagree:

![unregistered-trial-details](https://cloud.githubusercontent.com/assets/8862002/24805303/f1dfd374-1bb9-11e7-9f9f-f4f3748e327d.png)

**Comment by vitorbaptista** [comment]
@georgiana-b I prefer the first one, with the many "Unknown" values. Just missing an unknown in the "registration_date" and (possibly) conditions and interventions. It looks weird to have all those unknown values, but I think we'll iterate a few times on this UI, so happy to go with the easier solution here. I also agree that there's no need to change the trial details page.

I don't like the icon you used for source either, but I imagine we don't have a better one in our font. I think @nightsh added a new icon some time ago, otherwise we can ask @smth.

**Comment by nightsh** [comment]
I'm also voting for the second one :v:

As for the font, here's a quote of Sam's from the Slack channel:

> Easiest way to add icons to the font: Go to https://icomoon.io/app/ > Manage projects > Import project > Upload > https://github.com/opentrials/opentrials/blob/master/assets/fonts/opentrials/selection.json From there you can add icons from a range of collections, or upload SVGs.

**Comment by georgiana-b** [comment]
The icon in the photo was just for testing purposes. I'll add a new icon for source name and go with the first. Thanks guys!

**Comment by georgiana-b** [comment]
Closed via opentrials/opentrials#738, opentrials/opentrials-airflow#18 and opentrials/processors#120.
