### ISSUE TITLE
Deduplicate trials via title

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#661]
We currently only consider two trials to be the same if they share a common identifier. That gets many cases, but there're many others that we miss. We want to deduplicate as much trials as possible, but the cost of a false positive is high (as it adds noise to our discrepancies feature, for example), so we want to be conservative.

The current code lives on https://github.com/opentrials/processors/blob/4c359df7f258c6eb2dd64a6d4a1ccab3ba2410bc/processors/base/writers/trial.py, and uses `helpers.find_trial_by_identifiers()` to do the deduplication. In general, what we want to do in that method is:

1. Find if the trial already exists (currently only via identifiers, but potentially using other attributes as the title)
2. If it does, check if the current trial is higher priority than the one we have
2.1. If so, overwrite it
2.2. If not, move on.
3. If it doesn't, write the new trial

This task is to change step `1`, looking not only for the same identifiers but also the title. Look for exact matches at first. After that's done and merged, we can start developing fuzzy matching strategies.

# Requirements

* The number of false positives must be very low (ideally zero).
    If, in your tests, you see that there're many different trials with the same title, look for a different solution (e.g. adding other columns) and write your findings here.

* Log when a match was successful, and via which method (identifiers or title)

**Comment by vitorbaptista** [comment]
From the CSV @arthurSena, we could identify 3 titles that look invalid:

| count | scientific_title | example_url |
| --- | --- | --- |
| 1333 | [Trial of device that is not approved or cleared by the U.S. FDA] | https://clinicaltrials.gov/ct2/show/NCT03021707 |
| 909 | NA | http://apps.who.int/trialsearch/Trial3.aspx?trialid=PER-110-07 |
| 162 | See Detailed Description | https://api.opentrials.net/v1/trials/642a5890-6fd1-11e6-a625-0242ac12000b |

The example for "See Detailed Description" can only be checked via the DB, as we're only showing the `public_title`. This might mean that using `public_title` can be better than `scientific_title`, but that needs to be tested. Could you try it, @arthurSena?

**Comment by arthurSena** [comment]
@vitorbaptista we just built another CSV grouping by `public_title` that you can check [here](https://gist.github.com/arthurSena/39d2be0bbc0621448f9ab6cf6d4c8a6b). Also, we counted the number of groups in order to identify possible invalid titles:   

Count | public_title | example_url
------------ | ------------- | -------------
676 | [Trial of device that is not approved or cleared by the U.S. FDA] | https://clinicaltrials.gov/ct2/show/NCT02697604
21 | Not applicable | https://www.clinicaltrialsregister.eu/ctr-search/trial/2011-003047-22/DE
16 | Sun Protection Factor Assay | https://clinicaltrials.gov/ct2/show/NCT02803021
11 | Effect of supplementation in treatment of women with polycystic ovary syndrome | http://apps.who.int/trialsearch/Trial3.aspx?trialid=IRCT201508025623N48
10 | Effect of supplementation in treatment of polycystic ovary syndrome | http://apps.who.int/trialsearch/Trial3.aspx?trialid=IRCT201407115623N24
9 | Vaccine Therapy in Treating Patients With Metastatic Melanoma | http://apps.who.int/trialsearch/Trial3.aspx?trialid=NCT00019734
8 | not applicable | https://www.clinicaltrialsregister.eu/ctr-search/trial/2009-018118-21/CZ

You can check the whole grouping right [here](https://gist.github.com/arthurSena/26bf93b533517ca206d4371c20b2cc72)

Looking at these results we have the suspicion that `public_title` may produce a better outcome as it doesn't have as much invalid titles as the `scientific_title` one. What do you think ?

**Comment by vitorbaptista** [comment]
@arthurSena About `scientific_title` VS `public_title`, I'm happy to go with whatever you think is best, as you've been looking into this data for a while now. Another important thing is that if a trial has the same title (or whatever) but is considered as different trials by its registry, we must treat it as different trials as well. For instance, there're hundreds of trials with title `[Trial of device that is not approved or cleared by the U.S. FDA]` on CT.gov, but they're all different trials. Basically, the constraint is `record1.scientific_title == record2.scientific_title && record1.source_id != record2.source_id`.

I also assigned you to https://github.com/opentrials/opentrials/issues/676, for you to tackle after finishing this. Let me know if you have any questions.

**Comment by arthurSena** [comment]
@vitorbaptista Ok
 I will change my code to obey this constraint and do the pull request as soon as possible.
