### ISSUE TITLE
Some data contributions can't be downloaded, so they aren't processed

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#702]
For instance, the URL http://www.ebiomedicine.com/article/S2352-3964(16)30020-2/abstract is behind a paywall, so when we HEAD it to check its format, we don't get a response back. The solution here is to change our approach and instead of using HTTP HEAD, rely on the file extension to validate data.

**Comment by nightsh** [comment]
Should we flag them somehow is data is not accessible? I'm not saying to toggle the `approved` bit, but maybe there's a way to let curators know about it being unprocessable (and give them a chance to adjust the submission and – somehow – "mark" it for processing so it'll be picked up by the processor next time it runs).
My concern is that we'll probably gather a whole bunch of approved and unreachable contributions. Not sure how to deal with them, but by repeating the processing attempt every time the same, we certainly won't help much.

**Comment by vitorbaptista** [comment]
Agreed, we're missing some feedback for the curators. This feels like a separate issue, though, as I feel that contributing a paper that's behind a paywall wouldn't be rare (unfortunately). Could you open an issue for that?

**Comment by nightsh** [comment]
And close this one, or just try to do as you suggested in the description?

Another issue would be with confidentiality / licenses. If paywalled contributions are sent to us, then we won't be able to reupload them to a public location without breaking the commercial license that data might be having. Only solution I can see here is to upload to a restricted access storage, so only our processors and logged in curators could hit that.
Smells like Phase 2 to me.

**Comment by nightsh** [comment]
Pinging @vitorbaptista.

I would suggest to start drafting a few ideas for creating a contributor / curator / processor feedback loop. This can be done by:
* providing some way for curators to reach back to contributors and ask for more details
* contributions to be marked according to processing status: "ready for processing", "processed" and so on
* curators to be able to change the contribution processing status – for example, change it to "ready for processing" for any item that should be reprocessed
* contributors to have access to a list of their own submissions where they can
  * modify those still not moderated or rejected
  * delete unmoderated / rejectd
  * modifying an approved submisssion should still be possible, but I', not sure how at this point

As we can see, this is an entire new (and fun) feature to be built. I'd say paywalled contributions should be detected and ignored for now, then this issue closed. We should also start a new issue / epic containing the above items (and more related). WDYT?

P.S.: I love this feeling, when you work on a small issue that taps into a bigger one, then suddenly it makes a lot of overlooked things surface :smile:

**Comment by vitorbaptista** [comment]
So, I think we should link to paywalled data. It sucks, but it's better than not linking, and many academics have access to those via their institutions. The real issue here is that our code tries to hit the contributed links to determine the file's format. The fix IMHO is simply checking the file format via the file's extension. The other idea of having a feedback loop is independent to this task.

**Comment by georgiana-b** [comment]
> Some data contributions can't be downloaded so they aren't processed

The code is not trying to download the data. It just [checks the data is there](https://github.com/opentrials/processors/blob/master/processors/data_contributions/processor.py#L139).

@vitorbaptista The URL you give as an example doesn't fail due to wrong `Content-Type` or because it can't be downloaded.  It fails because the HEAD request returns status `405 - Method Not Allowed`. It was just their bad choice not allowing HEAD requests. A GET request with `requests` on that link returns a perfectly valid `text/html` data contribution (status `200`).

> The solution here is to change our approach and instead of using HTTP HEAD, rely on the file extension to validate data.

I chose the `Content-Type` approach to validation because IMO the first step in validating a data contribution is to make sure there is one :slightly_smiling_face:. The curators probably open the links thus filtering out most of the bad links but it's worth a double check since we don't process the data contributions immediately after being approved. Also, as a person that naively tried to validate content based on file extension, I think the `Content-Type` approach is more reliable and cleaner than the file extension one. 
So, as a solution to unfriendly websites that don't allow HEAD, I would suggest we try a GET request [if the HEAD request fails](https://github.com/opentrials/processors/blob/master/processors/data_contributions/processor.py#L142).

**Comment by vitorbaptista** [comment]
@georgiana-b I think a solution here could be:

```python
from contextlib import closing
try:
  with closing(requests.get(url, allow_redirects=True, stream=True)) as resp:
      return resp.headers.get('Content-Type')
except requests.exceptions.RequestException:
    pass
```

This means that we're using a GET request, but only downloading the headers (as it streams the contents). To make sure we don't get the contents, instead of returning the response itself, we return the actual `Content-Type` headers (or `None` if it doesn't exist). It should result in the same amount of data transferred as a HEAD request, but supporting servers that don't play by the rules.

What do you think?

**Comment by georgiana-b** [comment]
Great idea, we'll go with it. Thank you!
