### ISSUE TITLE
Add filter by source

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#708]
Add a filter that allows people picking which sources they'd want to search for. For the UI, you can use a similar implementation as the autocomplete boxes, but that doesn't allow writing new values (i.e. can only use valid names).

There's an endpoint on https://api.opentrials.net/v1/sources to get all of our sources, but be aware that not all sources are trial sources. We have things like `fda`, which shouldn't appear in this list. We might need to change our API responses to develop this feature. Please analyse the issue and write a proposal on the solution before developing it.

**Comment by nightsh** [comment]
Given the current `source` structure:

```javascript
  {
    "id": "nct",
    "name": "ClinicalTrials.gov",
    "source_url": "https://clinicaltrials.gov",
    "terms_and_conditions_url": "https://clinicaltrials.gov/ct2/about-site/terms-conditions",
    "type": "register"
  },
```

My proposal would be to only include sources that have `type === 'register'` in the dropdown.

**Comment by vitorbaptista** [comment]
@nightsh That won't work, unfortunatelly, as we also need to filter by PubMed, which isn't a register. Maybe we'd need a new type for PubMed, so it could be `type === 'register' OR type === 'pubmed-type'`

**Comment by nightsh** [comment]
Any idea of a name that would work? I can't think of anything.
But I can move on and develop the feature in the meantime, with a bogus name, waiting for a better idea or suggestion ;)
Other than that, was there anything else? I'll be starting on this shortly, it's quite an easy task that would likely improve the experience in a visible way.

**Comment by georgiana-b** [comment]
We already have a filter by registered/unregistered trials since #655. All unregistered trials come from `pubmed` so filtering by `unregistered` is equivalent with filtering by `source:pubmed`.
So considering this I think we should just add another filter `Registers` where people can choose one or more sources of type `register`.
Having these 2 filters is exactly what Jess proposed [here](https://github.com/opentrials/opentrials/issues/589#issuecomment-265210935).
