### ISSUE TITLE
Export data to a citation manager

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#9]
Presumably a major one, or some open format supported by several, if such a thing exists.

**Comment by pwalsh** [comment]
https://trello.com/c/3dS0DyNP/60-export-data-to-a-citation-manager

**Comment by benmeg** [comment]
@hash-bang has suggested we look at: https://github.com/hash-bang/Reflib-Node

"You may wish to look at Reflib-Node since you're already using a Node environment. It imports and exports citation libraries in a variety of formats as well as having various tooling to help work with them. Happy to work with you guys on other formats if needed."
